
name = "easyedit"
app = "api.index:app"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
  "fastapi>=0.121.0",
  "uvicorn>=0.34.0",
  "replicate",
  "python-dotenv",
  "python-multipart",
  "pillow",
  "numpy",
  "opencv-python-headless",
  "mediapipe",
]
